Repository graphql/graphql-relay-js, pull requests merged in 2021-06, with the labels that each got.

#335 package.json: Fix 'preversion' script
  package.json
Labels: PR: internal 🏠

#336 internal: Add workflow to check health of package-lock.json
  .github/workflows/ci.yml
  package-lock.json
Labels: PR: internal 🏠

#337 resources: Add script to generate changelog
  .eslintrc.yml
  resources/utils.js
Labels: PR: internal 🏠

#338 Add 'resources/gen-changelog.js' missing from #337
  resources/gen-changelog.js
Labels: PR: internal 🏠

#342 fix: convert number offset to string
  src/connection/arrayConnection.js
Labels: PR: polish 💅

#344 nodeDefinitions: Allow to pass number as ID values
  src/node/node.d.ts
  src/node/node.js
Labels: PR: feature 🚀

#345 Replace 'any' with 'mixed' in return types of various resolvers
  src/mutation/mutation.d.ts
  src/mutation/mutation.js
  src/node/plural.d.ts
  src/node/plural.js
Labels: PR: breaking change 💥

#346 Switch to custom base64 implementation
  .eslintrc.yml
  src/utils/__tests__/base64-test.js
  src/utils/base64.js
Labels: PR: breaking change 💥

#347 arrayConnection-test: improve readability and minimise duplication
  src/connection/__tests__/arrayConnection-test.js
Labels: PR: polish 💅

#348 arrayConnection: return all elements if cursors are on the outside
  src/connection/__tests__/arrayConnection-test.js
  src/connection/arrayConnection.js
Labels: PR: bug fix 🐞

#349 Allow mutations to return custom classes
  src/mutation/__tests__/mutation-test.js
  src/mutation/mutation.js
Labels: PR: bug fix 🐞

#350 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
  src/node/__tests__/plural-test.js
Labels: PR: dependency 📦

#351 Flow: switched to exact object by default
  .eslintrc.yml
  .flowconfig
  src/__tests__/starWarsData.js
  src/connection/arrayConnection.js
  src/connection/connection.js
  src/mutation/mutation.js
  src/node/node.js
  src/node/plural.js
Labels: PR: breaking change 💥
